### ISSUE TITLE
数据量少显示不了bug

### ISSUE THREAD

**Issue by r-kevinnnnnn** [iOSPrincekin/PrincekinKlineFrame#2]
在使用过程中,发现数据量少的时候,比如只有20条数据,数据就显示不了了.

**Comment by iOSPrincekin** [comment]
我将 PrincekinKlineFrameDemo 里面的data.json置为1条数据，发现也能显示正常，并未发现你说的数据量小无法显示的问题，你可亲自尝试。如果还有疑问，请加Wechat：15267030696
